<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: miércoles, 19 de junio de 2024 18:33:43</msg><msg code="-2147467259" type="100">Traceback (most recent call last):
  File "C:\Users\juaco\OneDrive\Documentos\ArcGIS\Packages\DAG_1s2024_L_TRABAJO_1_PARTE_2_JBV_d59d9f\p30\dag_1s2024_l_trabajo_1_parte_2_jbv.gdb\ALTURAS MANZ.py", line 35, in &lt;module&gt;
    arcpy.management.JoinField(fcIn, zone_field, fcIn2, fcOut, zone_field1, "MEAN")
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 9469, in JoinField
    raise e
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 9466, in JoinField
    retval = convertArcObjectToPythonObject(gp.JoinField_management(*gp_fixargs((in_data, in_field, join_table, join_field, fields, fm_option, field_mapping), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 512, in &lt;lambda&gt;
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000728: Field C:\Users\juaco\OneDrive\Documentos\ArcGIS\Packages\DAG_1s2024_L_TRABAJO_1_PARTE_2_JBV_d59d9f\p30\dag_1s2024_l_trabajo_1_parte_2_jbv.gdb\CAPAS_RESULTADOS\IND_RIESGO_MANZ_CODE_1 does not exist within table
ERROR 000800: The value is not a member of Select transfer fields | Use field mapping.
Failed to execute (JoinField).

</msg><msg code="0" type="0">Failed script 1.2.- Join Manzanas...</msg><msg code="-2147467259" type="100">Failed to execute (JOINMANZ).</msg><msg code="0" type="3">Failed at miércoles, 19 de junio de 2024 18:33:44 (Elapsed Time: 1.20 seconds)</msg></messages>